name: Publish

on:
  push:
    tags: [ "*" ]

jobs:
  build-macos-amd64:
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run:  gcc-13 -o loic-macos loic.c -static -s -lpthread
    - name: Upload to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos
        path: loic-macos

  build-macos-arm64:
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    runs-on: macos-14-arm64
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run:  gcc-13 -o loic-macos-arm64 loic.c -static -s -lpthread
    - name: Upload to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos
        path: loic-macos-arm64

  build-linux:
    needs: [build-macos-amd64, build-macos-arm64]
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      archs: >
        aarch64-linux-gnu
        alpha-linux-gnu
        arc-linux-gnu
        arm-linux-gnueabi
        hppa-linux-gnu
        i686-linux-gnu
        m68k-linux-gnu
        mips-linux-gnu
        mips64-linux-gnuabi64
        mips64el-linux-gnuabi64
        mipsel-linux-gnu
        mipsisa32r6-linux-gnu
        mipsisa32r6el-linux-gnu
        mipsisa64r6-linux-gnuabi64
        mipsisa64r6el-linux-gnuabi64
        powerpc-linux-gnu
        riscv64-linux-gnu
        s390x-linux-gnu
        sh4-linux-gnu
        sparc64-linux-gnu
    runs-on: ubuntu-latest
    container:
      image: amitie10g/cross-gcc:all
    steps:
    - name: Restore artifacts from macos
      uses: actions/download-artifact@v4
      with:
        name: macos
    - uses: actions/checkout@v4
    - name: Build
      run: |
        for arch in ${archs}; do
          ${arch}-gcc-13 -o loic-$(echo "${arch}" | cut -d '-' -f 1) loic.c -static -s -lpthread
        done
        arm-linux-gnueabihf-gcc-13 -o loic-armhf loic.c -static -s -lpthread
        x86_64-linux-gnu-gcc-13 -o loic loic.c -static -s -lpthread
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: "loic"
        tag: ${{ github.ref }}
        overwrite: true
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: "loic-*"
        tag: ${{ github.ref }}
        file_glob: true
        overwrite: true
    - name: Remove artifacts
      run: |
        curl \
          -X DELETE \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/artifacts/nombre-del-artifact
